Repository wecode-bootcamp-korea/27-westagram-backend-2-team, pull requests merged in 2021-11, with the labels that each got.

#1 [장도원] Mission 1: Django 초기 세팅
  students/dowon/westagram/.gitignore
  students/dowon/westagram/manage.py
  students/dowon/westagram/requirements.txt
  students/dowon/westagram/westagram/__init__.py
  students/dowon/westagram/westagram/asgi.py
  students/dowon/westagram/westagram/settings.py
  students/dowon/westagram/westagram/urls.py
  students/dowon/westagram/westagram/wsgi.py
Labels: Status: 수정 요청

#2 [이주명] Mission1: Django 초기 세팅
  students/jumyoeng/westagram/.gitignore
  students/jumyoeng/westagram/manage.py
  students/jumyoeng/westagram/requirements.txt
  students/jumyoeng/westagram/westagram/__init__.py
  students/jumyoeng/westagram/westagram/asgi.py
  students/jumyoeng/westagram/westagram/settings.py
  students/jumyoeng/westagram/westagram/urls.py
  students/jumyoeng/westagram/westagram/wsgi.py
Labels: Status: 멘토 리뷰 요청, Status: 피어 리뷰 요청

#4 [고민혁] Mission 1: Django 초기 세팅
  students/minhyukko/.gitignore
  students/minhyukko/manage.py
  students/minhyukko/requirements.txt
  students/minhyukko/westagram/__init__.py
  students/minhyukko/westagram/asgi.py
  students/minhyukko/westagram/settings.py
  students/minhyukko/westagram/urls.py
  students/minhyukko/westagram/wsgi.py
Labels: Status: 멘토 리뷰 요청, Status: 피어 리뷰 요청

#9 [성주호] Mission 1 : Django 초기 세팅
  students/jooho/.gitignore
  students/jooho/manage.py
  students/jooho/requirements.txt
  students/jooho/westagram/__init__.py
  students/jooho/westagram/asgi.py
  students/jooho/westagram/settings.py
  students/jooho/westagram/urls.py
  students/jooho/westagram/wsgi.py
Labels: Status: 멘토 리뷰 요청

#7 [고민혁] Mission 2 : 모델링
  students/minhyukko/users/__init__.py
  students/minhyukko/users/admin.py
  students/minhyukko/users/apps.py
  students/minhyukko/users/migrations/0001_initial.py
  students/minhyukko/users/migrations/__init__.py
  students/minhyukko/users/models.py
  students/minhyukko/users/tests.py
  students/minhyukko/users/views.py
  students/minhyukko/westagram/settings.py
  students/minhyukko/westagram/urls.py
Labels: Status: 멘토 리뷰 요청

#3 [유민혁] Mission 1 : Django 초기 세팅
  students/minhyeouk/.gitignore
  students/minhyeouk/manage.py
  students/minhyeouk/requirements.txt
  students/minhyeouk/westargram/__init__.py
  students/minhyeouk/westargram/asgi.py
  students/minhyeouk/westargram/settings.py
  students/minhyeouk/westargram/urls.py
  students/minhyeouk/westargram/wsgi.py
Labels: Status: 멘토 리뷰 요청, Status: 피어 리뷰 요청

#8 [장도원] Mission 2: 모델링
  students/dowon/users/__init__.py
  students/dowon/users/admin.py
  students/dowon/users/apps.py
  students/dowon/users/migrations/0001_initial.py
  students/dowon/users/migrations/__init__.py
  students/dowon/users/models.py
  students/dowon/users/tests.py
  students/dowon/users/urls.py
  students/dowon/users/views.py
  students/dowon/westagram/settings.py
Labels: Status: 멘토 리뷰 요청

#10 [이주명] Mission 2: 모델링
  students/jumyoeng/users/__init__.py
  students/jumyoeng/users/admin.py
  students/jumyoeng/users/apps.py
  students/jumyoeng/users/migrations/0001_initial.py
  students/jumyoeng/users/migrations/__init__.py
  students/jumyoeng/users/models.py
  students/jumyoeng/users/tests.py
  students/jumyoeng/users/views.py
  students/jumyoeng/westagram/settings.py
  students/jumyoeng/westagram/urls.py
Labels: Status: 멘토 리뷰 요청

#15 [장도원] Mission 3: 회원가입 기능 구현
  students/dowon/.vscode/settings.json
  students/dowon/users/migrations/0001_initial.py
  students/dowon/users/migrations/0002_alter_user_information.py
  students/dowon/users/models.py
  students/dowon/users/urls.py
  students/dowon/users/views.py
  students/dowon/westagram/urls.py
Labels: Status: 멘토 리뷰 요청

#17 [유민혁] Mission 3 : 회원가입 기능 구현
  students/minhyeouk/users/migrations/0001_initial.py
  students/minhyeouk/users/models.py
  students/minhyeouk/users/urls.py
  students/minhyeouk/users/views.py
  students/minhyeouk/westargram/settings.py
  students/minhyeouk/westargram/urls.py
Labels: Status: 멘토 리뷰 요청

#16 [이주명] Mission 3: 회원가입 기능 구현
  students/jumyoeng/users/migrations/0002_auto_20211119_0559.py
  students/jumyoeng/users/my_lib/validation.py
  students/jumyoeng/users/urls.py
  students/jumyoeng/users/views.py
  students/jumyoeng/westagram/urls.py
Labels: Status: 멘토 리뷰 요청

#18 [장도원] Mission 4: 로그인 기능 구현
  students/dowon/users/urls.py
  students/dowon/users/validation.py
  students/dowon/users/views.py
Labels: Status: 멘토 리뷰 요청

#24 [성주호] Mission 3: 회원가입 기능 구현
  students/jooho/users/urls.py
  students/jooho/users/views.py
Labels: Status: 멘토 리뷰 요청, Status: 피어 리뷰 요청

#21 [유민혁] Mission 4 : 로그인 기능 구현
  students/minhyeouk/users/urls.py
  students/minhyeouk/users/validation.py
  students/minhyeouk/users/views.py
Labels: Status: 수정 요청

#25 [고민혁] Mission 5: 회원가입 비밀번호 암호화 적용
  students/minhyukko/users/models.py
  students/minhyukko/users/views.py
Labels: Status: 멘토 리뷰 요청

#23 [장도원] Mission 5: 회원가입 비밀번호 암호화 적용
  students/dowon/users/views.py
Labels: Status: 멘토 리뷰 요청, Status: 피어 리뷰 요청
